services:
  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: helpdesk-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: helpdesk
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - helpdesk-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: helpdesk-server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8080
      MONGO_URI: mongodb://admin:password123@mongodb:27017/helpdesk?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000,http://localhost:80}
      AUTO_CLOSE_ENABLED: ${AUTO_CLOSE_ENABLED:-true}
      CONFIDENCE_THRESHOLD: ${CONFIDENCE_THRESHOLD:-0.78}
      STUB_MODE: ${STUB_MODE:-true}
      MAIL_FROM: ${MAIL_FROM:-noreply@helpdesk.local}
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - helpdesk-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/healthz', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: helpdesk-client
    restart: unless-stopped
    environment:
      VITE_API_BASE: ${VITE_API_BASE:-http://localhost:8080/api}
    ports:
      - "3000:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - helpdesk-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  helpdesk-network:
    driver: bridge