import mongoose from 'mongoose';

const ReplySchema = new mongoose.Schema({
  ticketId: { type: mongoose.Schema.Types.ObjectId, ref: 'Ticket', required: true },
  author: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, // null for system/AI replies
  authorType: { type: String, enum: ['user', 'agent', 'system'], required: true },
  body: { type: String, required: true },
  isAutoGenerated: { type: Boolean, default: false },
  agentSuggestionId: { type: mongoose.Schema.Types.ObjectId, ref: 'AgentSuggestion' }
}, { timestamps: true });

export const Reply = mongoose.model('Reply', ReplySchema);
